### ISSUE TITLE
No way to migrate contracts on docker 1.7.9-testnet

### ISSUE THREAD

**Issue by rozhkovdmitrii** [neonevm/neon-evm#310]
### Impact:
Proxy + testnet based Neon EVM <-> truffle compatibility

#### Start Solana node
```sh
docker run -p 8899:8899 -p 8900:8900 -p 8001:8001 -p 8000-8009:8000-8009/udp -ti -e RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bp
f_loader=debug,solana_rbpf=debug -e NDEBUG=1 --name=solana neonlabsorg/solana:v1.7.9-testnet | grep -v 'Program Vote111111111111111111111111111111111111111'
```
#### Start Neon EVM proxy

```sh
docker run  --rm -ti --network=host -e CONFIG=local -e EXTRA_GAS=10000 --name=proxy neonlabsorg/proxy:latest
```

#### Initialize empty truffle project

```sh
$ mkdir test-migration && cd test-migration
$ npm install web3 @truffle/hdwallet-provider
$ truffle init 
$ cp ../truffle-config.js ./
$ truffle --network solana migrate
```

> `truffle-config.js` is attached to this issue in archive. It will be needed to enter your own private Etherium keys

### Result:

```sh
$ truffle --network solana migrate

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at lastCompletedMigration (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:201:1)
    at Object.lastCompletedMigration (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:212:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Truffle v5.4.13 (core: 5.4.13)
Node v16.10.0
```

### Expected:

Migration with no errors

### Neon EVM Proxy log:

```log
2021-10-13 14:04:00,369 - pid:79 [D] run:63 - Start getting blocks
2021-10-13 14:04:00,397 - pid:79 [D] run:59 - Start indexing
2021-10-13 14:04:00,416 - pid:79 [D] gather_unknown_transactions:84 -   0 get_signatures_for_address 1000
2021-10-13 14:04:00,417 - pid:79 [D] gather_unknown_transactions:111 - start getting receipts
2021-10-13 14:04:00,418 - pid:79 [D] run:61 - Process receipts
2021-10-13 14:04:00,465 - pid:80 [I] access_log:226 - 127.0.0.1:53646 - POST /solana - 10010.49 ms
```

[truffle-config.zip](https://github.com/neonlabsorg/neon-evm/files/7338717/truffle-config.zip)

**Comment by rozhkovdmitrii** [comment]
f for some reasons you remove the Solana container and run it again then all related accounts, stored in foreign systems, get invalid from that moment. That's why you need to re-run proxy container and reset the state of Metamask and truffle as well, to make all relations consistent.

The Truffle state can be reset by redeploying in the following way: 

```sh
$ truffle migrate --network solana --reset
```
